"use client"

import 'bootstrap/dist/css/bootstrap.min.css';
import "bootstrap-icons/font/bootstrap-icons.css";
import 'aos/dist/aos.css';
import AOS from 'aos';
import { useEffect } from 'react';


// export const metadata = {
//   title: "YBF",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  useEffect(() => {
    AOS.init({ duration: 1000, once: true });
  }, []);

  return (
    <html lang="en">
      <head>
        <link href="/assets/img/favicon.png" rel="icon" />
        <link href="/assets/img/favicon.png" rel="apple-touch-icon" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"/>

        {/* <link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" />
        <link href="/assets/vendor/aos/aos.css" rel="stylesheet" /> */}
        <link href="/assets/css/main.css" rel="stylesheet" />
        <link href='/assets/css/resposiv.css' rel='stylesheet'/>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
